#!/usr/bin/ksh

while [[ $1 = -* ]]
do
	case $1 in
		-a ) print Option A processed
		     print \$1 equals ${1} ;;
		-b ) print Option B processed
		     print \$1 equals ${1}
		     shift
		     print Argument to B processed
		     print B-Argument equals ${1} ;;
		-c ) print Option C processed
		     print \$1 equals ${1} ;;
		*  ) print 'usage: bob [-a] [-b] [-c] args...'
			return 1
	esac
	shift
done
