#!/usr/bin/ksh

typeset GOAL=${1}
typeset HOURS=$(( ${GOAL} / 3600 ))
typeset PRE_MINUTES=$(( ${GOAL}  % 3600 ))
typeset MINUTES=$(( ${PRE_MINUTES}  / 60 ))
typeset SECONDS=$(( ${PRE_MINUTES} % 60 ))

#print "\tGOAL is: ${GOAL}"
#print "\tHOURS are: ${HOURS}"
#print "\tPRE_MINUTES are: ${PRE_MINUTES}"
#print "\tMINUTES are: ${MINUTES}"
#print "\tSECONDS are: ${SECONDS}"

typeset COUNT=0

#MANUAL_MONITOR=YES
print MANUAL_MONITOR is set to: ${MANUAL_MONITOR}
print $0 Starting at: $(date)

print "Sleeping ${GOAL} Seconds. ( ${HOURS} hrs ${MINUTES} min ${SECONDS} sec)"

COUNT_EM() {
if [[ ${MANUAL_MONITOR} = 'YES' ]]
then
	until [[ ${COUNT} -gt ${GOAL} ]] ## count up to GOAL
	do
		echo "\t\t${COUNT}\b\b\b\b\b\b\b\b\b\b\b\b\b\b\c"
		((COUNT+=1))	## increment COUNT by 1
		sleep 1		## Acutally do the sleep for 1 second.
	done
	print
else
	sleep ${GOAL}
	print
fi
}

COUNT_EM

print
print $0 Finished at: $(date)
