#!/usr/local/bin/expect -f
#
# This Expect script was generated by autoexpect on Thu May 22 14:46:48 2003
# Expect and autoexpect were both written by Don Libes, NIST.
#
# Note that autoexpect does not guarantee a working script.  It
# necessarily has to guess about certain things.  Two reasons a script
# might fail are:
#
# 1) timing - A surprising number of programs (rn, ksh, zsh, telnet,
# etc.) and devices discard or ignore keystrokes that arrive "too
# quickly" after prompts.  If you find your new script hanging up at
# one spot, try adding a short sleep just before the previous send.
# Setting "force_conservative" to 1 (see below) makes Expect do this
# automatically - pausing briefly before sending each character.  This
# pacifies every program I know of.  The -c flag makes the script do
# this in the first place.  The -C flag allows you to define a
# character to toggle this mode off and on.

set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

#
# 2) differing output - Some programs produce different output each time
# they run.  The "date" command is an obvious example.  Another is
# ftp, if it produces throughput statistics at the end of a file
# transfer.  If this causes a problem, delete these patterns or replace
# them with wildcards.  An alternative is to use the -p flag (for
# "prompt") which makes Expect only look for the last line of output
# (i.e., the prompt).  The -P flag allows you to define a character to
# toggle this mode off and on.
#
# Read the man page for more info.
#
# -Don


set timeout -1
spawn su - oracle
match_max 100000
expect -exact "(c)Copyright 1983-1997 Hewlett-Packard Co.,  All Rights Reserved.\r
(c)Copyright 1979, 1980, 1983, 1985-1993 The Regents of the Univ. of California\r
(c)Copyright 1980, 1984, 1986 Novell, Inc.\r
(c)Copyright 1986-1992 Sun Microsystems, Inc.\r
(c)Copyright 1985, 1986, 1988 Massachusetts Institute of Technology\r
(c)Copyright 1989-1993  The Open Software Foundation, Inc.\r
(c)Copyright 1986 Digital Equipment Corp.\r
(c)Copyright 1990 Motorola, Inc.\r
(c)Copyright 1990, 1991, 1992 Cornell University\r
(c)Copyright 1989-1991 The University of Maryland\r
(c)Copyright 1988 Carnegie Mellon University\r
(c)Copyright 1991-1997 Mentat, Inc.\r
(c)Copyright 1996 Morning Star Technologies, Inc.\r
(c)Copyright 1996 Progressive Systems, Inc.\r
(c)Copyright 1997 Isogon Corporation\r
\r
  \r
                           RESTRICTED RIGHTS LEGEND\r
Use, duplication, or disclosure by the U.S. Government is subject to\r
restrictions as set forth in sub-paragraph (c)(1)(ii) of the Rights in\r
Technical Data and Computer Software clause in DFARS 252.227-7013.\r
  \r
  \r
                           Hewlett-Packard Company\r
                           3000 Hanover Street\r
                           Palo Alto, CA 94304 U.S.A.\r
  \r
Rights for non-DOD U.S. Government Departments and Agencies are as set\r
forth in FAR 52.227-19(c)(1,2).\r
You have mail.\r
Which Oracle Version do you want to set the default home? \r
\r
(1) 8.0.5 (2) 8.1.7 (3)  9.2.0 "
send -- "x\r"
expect -exact "x\r
.profile:  Your environment is invalid : This is not an identifier.\r
\$ "
send -- ". ./.profile_9i\r"
expect -exact ". ./.profile_9i\r
\$ "
send -- "cd bin/sec\r"
expect -exact "cd bin/sec\r
\$ "
send -- "./ora_"
expect -exact " _"
send -- "stop_"
expect -exact " _"
send -- "backup\r"
expect -exact "backup\r
\$ "
send -- "exit\r"
expect eof
